### ISSUE TITLE
Handling of `OneOf`s 

### ISSUE THREAD

**Issue by afonsojramos** [udamir/api-smart-diff#8]
Handling of `OneOf`s seems incorrect as what ends up happening is that we get a removal and one replace per number of types of messages. I believe this happens for both AsyncAPIs and OpenAPIs.

Happy to help fix this, just give me some guidance :)

**Before**
```json
{
  "asyncapi": "2.4.0",
  "info": {
    "title": "Demo Removal of OneOf",
    "version": "1.0"
  },
  "defaultContentType": "application/json",
  "channels": {
    "topic": {
      "description": "description of topic",
      "publish": {
        "operationId": "ThankYou",
        "summary": "",
        "message": {
          "oneOf": [
            {
              "$ref": "#/components/messages/accountCreatedMessage"
            },
            {
              "$ref": "#/components/messages/accountUpdatedMessage"
            },
            {
              "$ref": "#/components/messages/exceptionMessage"
            }
          ]
        }
      }
    }
  },
  "components": {
    "schemas": {
      "accountCreatedMessage": {
        "id": "accountCreatedMessage",
        "type": "object",
        "description": "Account Created Message is published when an account is created.",
        "additionalProperties": false,
        "properties": {
          "accountId": {
            "type": "string",
            "description": "The account identifier as a GUID",
            "format": "guid"
          },
          "createdDate": {
            "type": "string",
            "description": "The date when the account is created",
            "format": "date-time"
          }
        }
      },
      "accountUpdatedMessage": {
        "id": "accountUpdatedMessage",
        "type": "object",
        "description": "Account updated message is a message that gets published when an account is updated\n            ",
        "additionalProperties": false,
        "properties": {
          "accountId": {
            "type": "string",
            "description": "The account identifier as a GUID",
            "format": "guid"
          }
        }
      },
      "exceptionMessage": {
        "id": "exceptionMessage",
        "type": "object",
        "description": "Interest exception message is sent when a service encounters an interest exception condition during its processing",
        "additionalProperties": false,
        "properties": {
          "accountId": {
            "type": "string",
            "description": "The unique internal identifier for the account",
            "format": "guid"
          },
          "reason": {
            "type": "string",
            "description": "The reason for the exception. Possible values: InvalidTemporaryRate"
          }
        }
      }
    },
    "messages": {
      "accountCreatedMessage": {
        "messageId": "AccountCreated",
        "payload": {
          "$ref": "#/components/schemas/accountCreatedMessage"
        },
        "name": "accountCreatedMessage",
        "summary": "Account Created Message is published when an account is created."
      },
      "accountUpdatedMessage": {
        "messageId": "AccountUpdated",
        "payload": {
          "$ref": "#/components/schemas/accountUpdatedMessage"
        },
        "name": "accountUpdatedMessage",
        "summary": "Account updated message is a message that gets published when an account is updated"
      },
      "exceptionMessage": {
        "messageId": "Exception",
        "payload": {
          "$ref": "#/components/schemas/exceptionMessage"
        },
        "name": "exceptionMessage",
        "summary": "Message sent when a service encounters an exception."
      }
    }
  }
}
```

**After**
```json
{
  "asyncapi": "2.4.0",
  "info": {
    "title": "Demo Removal of OneOf",
    "version": "1.0"
  },
  "defaultContentType": "application/json",
  "channels": {
    "topic": {
      "description": "description of topic",
      "publish": {
        "operationId": "ThankYou",
        "summary": "",
        "message": {
          "oneOf": [
            {
              "$ref": "#/components/messages/accountUpdatedMessage"
            },
            {
              "$ref": "#/components/messages/exceptionMessage"
            }
          ]
        }
      }
    }
  },
  "components": {
    "schemas": {
      "accountUpdatedMessage": {
        "id": "accountUpdatedMessage",
        "type": "object",
        "description": "Account updated message is a message that gets published when an account is updated\n            ",
        "additionalProperties": false,
        "properties": {
          "accountId": {
            "type": "string",
            "description": "The account identifier as a GUID",
            "format": "guid"
          }
        }
      },
      "exceptionMessage": {
        "id": "exceptionMessage",
        "type": "object",
        "description": "Interest exception message is sent when a service encounters an interest exception condition during its processing",
        "additionalProperties": false,
        "properties": {
          "accountId": {
            "type": "string",
            "description": "The unique internal identifier for the account",
            "format": "guid"
          },
          "reason": {
            "type": "string",
            "description": "The reason for the exception. Possible values: InvalidTemporaryRate"
          }
        }
      }
    },
    "messages": {
      "accountUpdatedMessage": {
        "messageId": "AccountUpdated",
        "payload": {
          "$ref": "#/components/schemas/accountUpdatedMessage"
        },
        "name": "accountUpdatedMessage",
        "summary": "Account updated message is a message that gets published when an account is updated"
      },
      "exceptionMessage": {
        "messageId": "Exception",
        "payload": {
          "$ref": "#/components/schemas/exceptionMessage"
        },
        "name": "exceptionMessage",
        "summary": "Message sent when a service encounters an exception."
      }
    }
  }
}
```

**Diff**
```json
[
  {
    "path": [
      "channels",
      "topic",
      "publish",
      "message",
      "oneOf",
      2
    ],
    "before": {
      "$ref": "#/components/messages/exceptionMessage"
    },
    "action": "remove",
    "type": "unclassified"
  },
  {
    "path": [
      "channels",
      "topic",
      "publish",
      "message",
      "oneOf",
      0,
      "$ref"
    ],
    "before": "#/components/messages/accountCreatedMessage",
    "after": "#/components/messages/accountUpdatedMessage",
    "action": "replace",
    "type": "unclassified"
  },
  {
    "path": [
      "channels",
      "topic",
      "publish",
      "message",
      "oneOf",
      1,
      "$ref"
    ],
    "before": "#/components/messages/accountUpdatedMessage",
    "after": "#/components/messages/exceptionMessage",
    "action": "replace",
    "type": "unclassified"
  },
  {
    "path": [
      "components",
      "schemas",
      "accountCreatedMessage"
    ],
    "before": {
      "id": "accountCreatedMessage",
      "type": "object",
      "description": "Account Created Message is published when an account is created.",
      "additionalProperties": false,
      "properties": {
        "accountId": {
          "type": "string",
          "description": "The account identifier as a GUID",
          "format": "guid"
        },
        "createdDate": {
          "type": "string",
          "description": "The date when the account is created",
          "format": "date-time"
        }
      }
    },
    "action": "remove",
    "type": "unclassified"
  },
  {
    "path": [
      "components",
      "messages",
      "accountCreatedMessage"
    ],
    "before": {
      "messageId": "AccountCreated",
      "payload": {
        "$ref": "#/components/schemas/accountCreatedMessage"
      },
      "name": "accountCreatedMessage",
      "summary": "Account Created Message is published when an account is created."
    },
    "action": "remove",
    "type": "unclassified"
  }
]
```

**Comment by udamir** [comment]
Hi! Thank you for issue. I will check and come back shortly.

**Comment by udamir** [comment]
please check api-smart-diff@1.0.4, hope I fixed the issue

**Comment by afonsojramos** [comment]
Sorry, but it doesn't seem like it got fixed, at least in the example I gave here.

Looking at the commit you pushed, the tests seem to indeed test the feature correctly however. But upon testing the example above, I still get the same error. :/

**Comment by udamir** [comment]
fixed in api-smart-diff@1.0.6
The rules for asyncApi 2.x are not tested properly, so there may be many similar issues. I would be grateful if you could help with testing current rules, or even contribute your version of asyncApi rules.

**Comment by afonsojramos** [comment]
Sure thing! A lot of things are currently `unclassified` from what I see, so yeah, definitely room for improvement! I'll take a look, thanks!
